
language: ruby
rvm:
    - 2.5.1
    # - ruby-head
env:
  global:
    MYSQL_SOCKET='~travis/.my.cnf'
services:
    - mysql
before_script:
    - bundle install
script:
    - bundle exec rails db:create RAILS_ENV=test
    - bundle exec rails db:migrate RAILS_ENV=test
    - bundle exec rspec --color --require spec_helper --format progress spec
    - bundle exec rubocop
